### ISSUE TITLE
example MPT quantization doesn't work

### ISSUE THREAD

**Issue by havietisov** [ggerganov/ggml#360]
Followed this guide : https://github.com/ggerganov/ggml/tree/master/examples/mpt
When tried to cast model to fp-16, got following error : 
* Loading part: pytorch_model-00001-of-00007.bin
Traceback (most recent call last):
  File "/mnt/j/ggml/examples/mpt/convert-h5-to-ggml.py", line 133, in <module>
    model_part = torch.load(f"{dir_model}/{part_name}", map_location="cpu")
  File "/home/_username/.local/lib/python3.10/site-packages/torch/serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/_username/.local/lib/python3.10/site-packages/torch/serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

Maybe guide/code should be updated

**Comment by klosax** [comment]
> * _pickle.UnpicklingError: invalid load key, 'v'.

It looks like your model files are corrupted. Try download them again.
